name: Test application

on:
  pull_request:
    branches: [ qa ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CHANGE_MINIKUBE_NONE_USER: true
    strategy:
      matrix:
        jdk: [ 8 ]
    defaults:
      run:
        working-directory: finish
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - run: unset _JAVA_OPTIONS
    - name: Run tests
      run: sudo ../scripts/testApp.sh
    - name: Post tests
      if: always()
      run: docker images
